pipeline {
    agent any
    environment {
        DOCKER_CREDENTIALS = 'docker-credentials'
        image = "juancastaneda20/auth"
        dockerImage = ''
        }
    stages {
        stage('build'){
            steps {
                sh 'cd auth'
                script {
                    dockerImage = docker.build image + ':' + env.GIT_COMMIT
                }
            }              
        }
        stage('Push the image') {
            steps {
                echo 'Pushing image'
                script {
                    docker.withRegistry( '', DOCKER_CREDENTIALS) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage ('Remove the images'){
            steps{
                sh 'docker rmi ' + image + ':' + env.GIT_COMMIT
            }    
        }
        stage ('Deploy') {
            steps {
                sh 'echo hola'
            }
        }
    }
}
