//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.24 at 08:22:05 PM COT 
//


package com.flying.seeker;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Review complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Review">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="comentary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stars" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Review", propOrder = {
    "comentary",
    "stars"
})
public class Review {

    @XmlElement(required = true)
    protected String comentary;
    protected int stars;

    /**
     * Gets the value of the comentary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComentary() {
        return comentary;
    }

    /**
     * Sets the value of the comentary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComentary(String value) {
        this.comentary = value;
    }

    /**
     * Gets the value of the stars property.
     * 
     */
    public int getStars() {
        return stars;
    }

    /**
     * Sets the value of the stars property.
     * 
     */
    public void setStars(int value) {
        this.stars = value;
    }

}
